services:
  - type: web
    name: iot-pastebin
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: RENDER
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: pastebindb  # must match your database service name
          property: connectionString